FROM debian:10-slim

ENV tmp_dir /tmp
WORKDIR /tmp

ADD APIs/Employee.json Employee.json

RUN apt-get update \
  && apt-get install -y curl \
  && curl -sL https://deb.nodesource.com/setup_12.x | bash - \
  && apt-get install -y nodejs

RUN npm install -g json-server

ENTRYPOINT ["json-server", "--id", "EmpId", "--port", "8082", "--host", "0.0.0.0", "--watch", "Employee.json"]

CMD ["/tmp/Employee.json"]